// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMrphSvXuzMha244wr02RSoz3xdihIywQ',
    appId: '1:1000640266850:web:7c9a918b81bbf343f7c73b',
    messagingSenderId: '1000640266850',
    projectId: 'tsukimon-d68b9',
    authDomain: 'tsukimon-d68b9.firebaseapp.com',
    storageBucket: 'tsukimon-d68b9.appspot.com',
    measurementId: 'G-SVZ29ED138',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmLqWaDD5TMYVffH37sayLChQpGaAdwvg',
    appId: '1:1000640266850:android:eff38c3d7797c0aaf7c73b',
    messagingSenderId: '1000640266850',
    projectId: 'tsukimon-d68b9',
    storageBucket: 'tsukimon-d68b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkPj2Ee1Dd-wN88vEt3eQ0RnC71fh0IsY',
    appId: '1:1000640266850:ios:e4cf7a8972f9e697f7c73b',
    messagingSenderId: '1000640266850',
    projectId: 'tsukimon-d68b9',
    storageBucket: 'tsukimon-d68b9.appspot.com',
    iosClientId: '1000640266850-2e2run090oq6r1de4k86fa3rsiondltp.apps.googleusercontent.com',
    iosBundleId: 'com.tsukimon.tsukimon',
  );
}
